<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RobotGameData</AssemblyName>
    <RootNamespace>RobotGameData</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);MONOGAME;MONOGAME_GL</DefineConstants>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>bin\MonoGameGL\$(Configuration)</OutputPath>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DigitalRiseModel.MonoGame" Version="0.6.0" />
    <PackageReference Include="XNAssets.FontStashSharp.MonoGame" Version="0.7.7" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4" />
  </ItemGroup>
</Project>
