<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RobotGameData</AssemblyName>
    <RootNamespace>RobotGameData</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);MONOGAME;MONOGAME_DX</DefineConstants>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputPath>bin\MonoGameDX\$(Configuration)</OutputPath>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NursiaModel.MonoGame" Version="0.6.1" />
    <PackageReference Include="XNAssets.FontStashSharp.MonoGame" Version="0.7.7" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4" />
  </ItemGroup>
</Project>
